# Generated by Django 3.1.1 on 2022-12-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
